schema_version: 1

context:
  name: mutmut
  version: 3.3.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 6aabc3a8f2b6c8eafe7054e1f7348e68aba807dcf12bffb6bfa00e5046d8a6bd

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - mutmut = mutmut.__main__:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - libcst 1.7*
    - click
    - textual
    - setproctitle
    - toml >=0.10.2
    - pytest

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - mutmut --help

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: mutmut - python mutation tester
  description: |
    Mutmut is a mutation testing system for Python,
    with a strong focus on ease of use.
  homepage: https://github.com/boxed/mutmut
  repository: https://github.com/boxed/mutmut
  documentation: https://mutmut.readthedocs.io/

extra:
  recipe-maintainers:
    - carlodri
